### ISSUE TITLE
env.php.warden.php Error on init.sh

### ISSUE THREAD

**Issue by joesken** [davidalger/warden-env-magento2#4]
Hi,

Firstly thanks for all this - looks great. I'm busy working my way through the documentation and this template to try things out. 

When I run the ./tools/init.sh --db-dump command it gives the error below coming from https://github.com/davidalger/warden-env-magento2/blob/develop/tools/init.sh#L117 I think:

==> [19:19:57] Verifying configuration
ERROR: Missing local file: ./webroot/app/etc/env.php.warden.php

I may be misunderstanding this but I'm not clear where this file should come from (in the webroot there is only the env.php.init.php file).   For background I'm trying to setup an existing project.

If you could point me in the right direction please, thanks.

Joseph

**Comment by davidalger** [comment]
The file at `./webroot/app/etc/env.php.warden.php` generally comes from the initial setup process. That is to say, when you run `./tools/init.sh` without the `./webroot/composer.json` present (as it won't be when you first clone this repo) you'd see the following msg:

```
WARNING: Implying --clean-install since file ./webroot/composer.json not present
```

Under this condition, the script first installs Magento from the composer meta package and then runs `bin/magento setup:install ...` and merges in the contents of `webroot/app/etc/env.php.init.php` storing the result at `./webroot/app/etc/env.php.warden.php` with the intent that this file be committed to version control. On subsequent setups, when this file and `composer.json` already exist, the init script symlinks `env.php` to `env.php.warden.php` and imports the database rather than running an install routine.

Since it sounds like you already have placed the `composer.json` and related files into the webroot from your existing project, what you should be able to do is this:

a) First run with the `--clean-install` flag to initialize a clean database via setup:install and generate the `env.php.warden.php` file (be sure to commit this).

b) Run the `./tools/init.sh --db-dump` command you ran previously to import your database onto the project.

I had not honestly thought about using this repo as a template for importing an existing project, so it's geared more towards new project setups. In case the above does not work, I've attached what the resulting `env.php.warden.php` file would look like on a clean install of Magento 2.3.4 using this project template for you to copy into your project (updating domain names in the file as needed).

[env.php.warden.php.zip](https://github.com/davidalger/warden-env-magento2/files/4390917/env.php.warden.php.zip)
