### ISSUE TITLE
init script error

### ISSUE THREAD

**Issue by christian-walker** [davidalger/warden-env-magento2#7]
When I run this script on the newest version of warden I get this error message:
```
`tools/init.sh: line 26: `::': not a valid identifier`
```

so I changed this to `wardenEcho`  and all other references to this method and then it worked.  Not sure if anyone else ran into this issue before ,but if so, this was my solution.

Before
```
function :: {
  echo
  echo "==> [$(date +%H:%M:%S)] $@"
}
```

After
```
function wardenEcho {
  echo
  echo "==> [$(date +%H:%M:%S)] $@"
}
```

**Comment by davidalger** [comment]
@christian-walker What version of bash do you run? You can find this via `bash --version`

Asking as I've never seen this error before, and have used `::` as a function name in tons of scripts all over the place internally over here without issue. Tried to reproduce this on `3.2.57` (ships with macOS Catalina) and also `5.0.17` as available via brew.

**Comment by christian-walker** [comment]
@davidalger  I'm on 
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by davidalger** [comment]
@christian-walker I did a good amount of digging here, and what I found is, the use of `::` as a function name is completely acceptable in `bash` _unless_ it's running in POSIX mode. The `sh` shell wouldn't allow it for example, and `sh` similarly doesn't allow using `_` in function names (a practice which is pretty pervasive in bash completion scripts). I.e. it's not a matter of bash version at issue here, but it sounds like something is throwing your shell into POSIX mode, whether that is `bash` being run in posix mode somehow. Rather than adjust the script (which specifies std bash in the shebang) to adopt posix-only support, I'd suggest perhaps trying to determine what is causing your system to run in posix only mode.

On my Mac:
```
$ sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
$ sh -c 'function :: { echo test; }; ::'
sh: `::': not a valid identifier

$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
$ bash --posix -c 'function :: { echo test; }; ::'
bash: `::': not a valid identifier
$ bash -c 'function :: { echo test; }; ::' --posix
test
```

I wasn't just satisfied testing on my Mac, so I tested the same on Linux:
```
$ sh --version
GNU bash, version 5.0.11(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ sh -c 'function :: { echo test; }; ::'
sh: `::': not a valid identifier
$ bash --version
GNU bash, version 5.0.11(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ bash --posix -c 'function :: { echo test; }; ::'
bash: `::': not a valid identifier
$ bash -c 'function :: { echo test; }; ::'
test
```

You can see from the output in all cases it works in bash unless --posix is specified, and it does not work in `sh` (which as can be seen from the version output, is basically bash running in posix only mode on both Mac OS and on Fedora)
